### ISSUE TITLE
Logo not showing on phone browser

### ISSUE THREAD

**Issue by prrvchr** [BDHU/minimalist#10]
Hi,

First of all thank you for this great theme.

I just updated [my site](https://prrvchr.github.io/OAuth2OOo/) and noticed that the logo is not displayed in Firefox on my phone...

**Comment by BDHU** [comment]
I removed it because it was too big in my setup. However, it's pretty easy to add it back. [This line](https://github.com/BDHU/minimalist/blob/main/_sass/jekyll-theme-minimalist.scss#L263) prevents image from displaying if the screen size is less than certain threshold. You can simply remove it to display the logo on your phone.

**Comment by prrvchr** [comment]
Hi BDHU,

Thank you for the info.
I even managed to get the logo, which is in svg, to follow the dark theme of the browser.
Great job, thanks again.
